# Generated by Django 4.2.2 on 2023-06-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=20)),
                ('weather', models.CharField(max_length=30)),
                ('temp', models.IntegerField()),
                ('temp_feel', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('sunrise', models.TimeField()),
                ('sunset', models.TimeField()),
                ('metric', models.CharField(max_length=20)),
                ('question_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-question_time',),
            },
        ),
    ]
