# Generated by Django 4.2.2 on 2023-06-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherhistory',
            name='country',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
