# Generated by Django 4.2.2 on 2023-06-22 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_alter_weatherhistory_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherhistory',
            old_name='metric',
            new_name='unit',
        ),
    ]
